name: Pull Request build

on:
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  determine_build:
    name: Determine builds to run
    runs-on: ubuntu-latest

    outputs:
      mobile: ${{ steps.changes.outputs.mobile }}
      functions: ${{ steps.changes.outputs.functions }}

    steps:
      - id: changes
        name: Paths Changes Filter
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            mobile:
              - "lib/**"
              - "ios/**"
              - "android/**"
            functions:
              - "functions/**"

  android_build:
    name: Android Build
    runs-on: ubuntu-latest

    needs: determine_build
    if: needs.determine_build.outputs.mobile == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Linting
        run: flutter analyze

      # - name: Run tests
      #   run: flutter test

  functions_test:
    name: Functions Test
    runs-on: ubuntu-latest

    needs: determine_build
    if: needs.determine_build.outputs.functions == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn
        working-directory: functions

      - name: Run tests
        run: yarn test
        working-directory: functions

