
name: Staging Deployment

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.md"

  workflow_dispatch:

jobs:
  android_build:
    name: Android Mobile Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"

      - name: Add Github signer properties file
        id: exc_github_signer_properties
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "key.properties"
          fileDir: "android"
          encodedString: ${{ secrets.EXC_GITHUB_SIGNER_PROPERTIES }}

      - name: Add Github signer keystore
        id: exc_github_signer_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileDir: "android/app"
          fileName: "github-keystore.jks"
          encodedString: ${{ secrets.EXC_GITHUB_SIGNER_KEYSTORE }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android app
        run: flutter build apk

      - name: "Tar files"
        run: tar -cvf artifacts.tar build/app/outputs/flutter-apk/*.apk

      - name: Upload Android apk
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.tar
          retention-days: 1

  functions_build:
    name: Functions build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXCEL_ACADEMY_ONLINE }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Install firebase
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: yarn
        working-directory: functions

      - name: Firebase deploy functions
        run: |
          firebase deploy \
              --only functions \
              --project=excel-academy-online

  configurations_deploy:
    name: Firebase configurations deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXCEL_ACADEMY_ONLINE }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Install firebase
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: yarn
        working-directory: functions

      - name: Firebase deploy functions
        run: |
          firebase deploy \
              --only database,firestore,remoteconfig,storage \
              --project=excel-academy-online

  android_deploy:
    name: Android Mobile Deploy

    needs: android_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Untar Artifacts
        run: tar -xvf artifacts.tar

      - id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXCEL_ACADEMY_ONLINE }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - id: message
        name: Get commit message
        run: echo message=$(git tag -l --format='%(contents)'${REF}) >> "$GITHUB_OUTPUT"
        env:
          REF: ${{ github.event.push.after }}

      - name: Install firebase
        run: npm install -g firebase-tools

        # Deploy to only staging users
      - name: Deploy Android app to Firebase app distribution
        env:
          message: ${{ steps.message.outputs.message }}
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
              --project=excel-academy-mobile \
              --app 1:1027112230279:android:7d45ccd3b9d0f816f9c722 \
              --release-notes "$message" \
              --groups "staging, admin"

  # webapp_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: npm ci && npm run build
  #     - uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: "${{ secrets.GITHUB_TOKEN }}"
  #         firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXCEL_ACADEMY_ONLINE }}"
  #         channelId: live
  #         projectId: excel-academy-online

